: FIB 0 1 ROT BEGIN ?DUP 0= IF DROP SWAP DROP EXIT THEN -ROT 2DUP + ROT DROP ROT 1- AGAIN ;
37 FIB . BYE
\TIME FIBTEST
\." s: " U. ." us: " U. CR
\BYE
\: FIB 0 1 ROT BEGIN ?DUP 0= IF DROP SWAP DROP EXIT THEN -ROT 2DUP SWAP U. U. 58 EMIT SPACE 2DUP + DUP U. CR ROT DROP ROT 1- AGAIN ;

